=== iwannabedeewo/thesis-work/resources/zamek_xml/dtd/config.dtd
<!--
DTD for monitor config.xml
-->
<!ELEMENT root (user,support?,configuration)>

<!ELEMENT user (contact+)>

<!ATTLIST user
  name CDATA #REQUIRED
  country CDATA #IMPLIED 
  language CDATA #IMPLIED 
  place CDATA #REQUIRED
  address CDATA #IMPLIED 
  tel CDATA #IMPLIED 
  sim CDATA #IMPLIED 
  modemTel CDATA #IMPLIED 
  email CDATA #IMPLIED >

<!ELEMENT contact (#PCDATA)>
<!ATTLIST contact
  name CDATA #REQUIRED
  tel CDATA #IMPLIED
>

<!ELEMENT support EMPTY>
<!ATTLIST support
  lan ( true | false ) #REQUIRED 
  email CDATA #IMPLIED
  tel CDATA #IMPLIED
>

<!ELEMENT configuration (pages? , specials? , global , devices , sequences , tasks)>

<!ELEMENT pages (page+)>

<!ELEMENT page EMPTY>
<!ATTLIST page
  name CDATA #REQUIRED>

<!ELEMENT specials (slider-group+)>

<!ELEMENT slider-group (#PCDATA)>
<!ATTLIST slider-group
  index NMTOKEN #REQUIRED
  slider-counts NMTOKEN #REQUIRED
  x-coord NMTOKEN #REQUIRED
  y-coord NMTOKEN #REQUIRED
  width NMTOKEN #REQUIRED
  height NMTOKEN #REQUIRED
  page NMTOKEN #REQUIRED
  orientation ( horizontal | vertical ) #REQUIRED
  format CDATA #REQUIRED>

<!ELEMENT global (#PCDATA)>
<!ATTLIST global
  writeBase NMTOKEN #REQUIRED
  readBase NMTOKEN #REQUIRED>

<!ELEMENT devices (silo* , offsetCorrector* , targetSilo* , ponderingSilo* , redler* , elevator* ,
      cleaner* , mplexer* , valve*)>
<!ATTLIST devices
  writeBase NMTOKEN #REQUIRED
  readBase NMTOKEN #REQUIRED>
 
<!ELEMENT silo (img,level)>
<!ATTLIST silo
  name CDATA #REQUIRED
  plcIndex NMTOKEN #REQUIRED
  page NMTOKEN #REQUIRED
  default-product CDATA #IMPLIED
  target-confirm ( true | false ) #IMPLIED
  product-admin ( true | false ) #REQUIRED 
  product-label-x NMTOKEN #REQUIRED
  product-label-y NMTOKEN #REQUIRED
  tag-x NMTOKEN #REQUIRED
  tag-y NMTOKEN #REQUIRED>

<!ELEMENT level (full*,empty*)>
<!ATTLIST level
  name CDATA #IMPLIED
  checking ( none | switching | full-only ) #REQUIRED
  full-is-off-task ( true | false ) #IMPLIED
  img-x NMTOKEN #IMPLIED 
  img-y NMTOKEN #IMPLIED 
  test NMTOKEN #IMPLIED>

<!ELEMENT full (#PCDATA)>
<!ATTLIST full
  name CDATA #REQUIRED 
  img-x NMTOKEN #REQUIRED 
  img-y NMTOKEN #REQUIRED 
  maxthresold NMTOKEN #REQUIRED>

<!ELEMENT empty (#PCDATA)>
<!ATTLIST empty
  name CDATA #REQUIRED 
  img-x NMTOKEN #REQUIRED 
  img-y NMTOKEN #REQUIRED 
  minthresold NMTOKEN #REQUIRED>

<!ELEMENT img (#PCDATA)>
<!ATTLIST img
  name CDATA #REQUIRED
  img-x NMTOKEN #REQUIRED 
  img-y NMTOKEN #REQUIRED>

<!ELEMENT offsetCorrector (#PCDATA)>
<!ATTLIST offsetCorrector
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED   
  page NMTOKEN #REQUIRED  
  receiveCorrection NMTOKEN #REQUIRED  
  transmitCorrection NMTOKEN #REQUIRED>

<!ELEMENT targetSilo (img,level)>
<!ATTLIST targetSilo
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED  
  page NMTOKEN #REQUIRED  
  permeability NMTOKEN #IMPLIED>

<!ELEMENT ponderingSilo (level,img,scale,remote-server)>
<!ATTLIST ponderingSilo
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED 
  page NMTOKEN #REQUIRED 
  format CDATA #REQUIRED 
  label-x NMTOKEN #REQUIRED 
  label-y NMTOKEN #REQUIRED
  empty-limit NMTOKEN #REQUIRED 
  full-limit NMTOKEN #REQUIRED 
  product-admin ( true | false ) #REQUIRED
  product-label-x NMTOKEN #REQUIRED 
  product-label-y NMTOKEN #REQUIRED>

<!ELEMENT scale (#PCDATA)>
<!ATTLIST scale
  type CDATA #REQUIRED 
  name CDATA #REQUIRED  
  port CDATA #REQUIRED  
  address CDATA #REQUIRED  
  divide NMTOKEN #REQUIRED 
  max-load NMTOKEN #REQUIRED  
  input-format CDATA #REQUIRED 
  test NMTOKEN #IMPLIED>

<!ELEMENT remote-server (#PCDATA)>
<!ATTLIST remote-server
  port NMTOKEN #REQUIRED>

<!ELEMENT redler (variableSpeed?, img, slider?)>
<!ATTLIST redler
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED  
  page NMTOKEN #REQUIRED>

<!ELEMENT variableSpeed (#PCDATA)>
<!ATTLIST variableSpeed
  mode ( none | modbusPlc ) #REQUIRED 
  frequenceStep NMTOKEN #REQUIRED
  relativeToMinFrequence ( true | false ) #REQUIRED
  minFrequence NMTOKEN #REQUIRED 
  maxFrequence NMTOKEN #REQUIRED>

<!ELEMENT slider (#PCDATA)>
<!ATTLIST slider
  index NMTOKEN #REQUIRED>

<!ELEMENT elevator (img+)>
<!ATTLIST elevator
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED  
  page NMTOKEN #REQUIRED>

<!ELEMENT cleaner (img)>
<!ATTLIST cleaner
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED  
  hidden ( true | false ) #IMPLIED
  page NMTOKEN #REQUIRED>

<!ELEMENT mplexer (img)>
<!ATTLIST mplexer
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED  
  page NMTOKEN #REQUIRED
  maxDirection NMTOKEN #REQUIRED 
  subType NMTOKEN #REQUIRED>

<!ELEMENT valve (img)>
<!ATTLIST valve
  name CDATA #REQUIRED 
  plcIndex NMTOKEN #REQUIRED  
  page NMTOKEN #REQUIRED>

<!ELEMENT sequences (device+)>

<!ELEMENT device (next+)>
<!ATTLIST device
  name CDATA #REQUIRED>

<!ELEMENT next (#PCDATA)>

<!ELEMENT tasks (task+)>

<!ELEMENT task (source+)>
<!ATTLIST task
  name CDATA #REQUIRED 
  readBase NMTOKEN #REQUIRED  
  index NMTOKEN #REQUIRED   
  checked ( true | false ) #REQUIRED 
  checkProduct ( true | false ) #IMPLIED
  max-sources NMTOKEN #IMPLIED>

<!ELEMENT source (#PCDATA)>

=== iwannabedeewo/thesis-work/resources/zamek_xml/src/conf.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE root SYSTEM "../dtd/config.dtd">

<root>
	<user name="Acme Corp." country="Hu" language="hu" place="Anywhere" address=" " tel=" " sim="-" modemTel="-" email=" ">
	     <contact name="XXX" tel="555-55555"/>
	     <contact name="YYY" tel="555-55556"/>
	     <contact name="muszak" tel="555-55557"/>
	</user>
	
	<support lan="true" email="q@q.q" tel="555-44444"/>
		
	<configuration>
		<pages>
		  <page name="Liszt"/>
			<page name="Korpa"/>
		</pages>
	
		<specials>
			<!-- slider-group index="0" slider-counts="2" x-coord="200" y-coord="900"  width="280" 
						  height="120" page="0" orientation="horizontal" format="%2d"/> -->
			<slider-group index="0" slider-counts="2" x-coord="200" y-coord="50"  width="280" 
						  height="120" page="0" orientation="horizontal" format="%2d"/>
						  
						  
			<!-- slider-group index="1" slider-counts="2" x-coord="1050" y-coord="900" width="280" 
						  height="120" page="0" orientation="horizontal" format="%2d"/> -->
			<slider-group index="1" slider-counts="2" x-coord="1050" y-coord="50" width="280" 
						  height="120" page="0" orientation="horizontal" format="%2d"/>
		</specials>
		
	    <global writeBase="0" readBase="400"/>
			
	    <devices writeBase ="11" readBase="411">

			<silo name="s1" plcIndex="0"  page="0"  default-product="bl80" target-confirm="true"
				product-admin="true" product-label-x="153" product-label-y="450"
				tag-x="153" tag-y="460">
				<img name="s1" img-x="153" img-y="565"/>
				<level checking="none" />		
			</silo>	            
			   
			<silo name="s2" plcIndex="1"  page="0"  target-confirm="true"
				product-admin="true" product-label-x="210" product-label-y="450"
				tag-x="210" tag-y="460">
				<img name="s2" img-x="210" img-y="565"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s3" plcIndex="2"  page="0"  target-confirm="true" 
				product-admin="true" product-label-x="251" product-label-y="450"
				tag-x="251" tag-y="460">
				<img name="s3" img-x="251" img-y="565"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s4" plcIndex="3"  page="0" target-confirm="true"
				product-admin="true" product-label-x="291" product-label-y="450"
				tag-x="291" tag-y="460">
				<img name="s4" img-x="291" img-y="565"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s5" plcIndex="4"  page="0" target-confirm="true"
				product-admin="true" product-label-x="331" product-label-y="450"
				tag-x="331" tag-y="460">
				<img name="s5" img-x="331" img-y="565"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s6" plcIndex="5"  page="0" target-confirm="true"
				product-admin="true" product-label-x="371" product-label-y="450"
				tag-x="371" tag-y="460">
				<img name="s6" img-x="371" img-y="565"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s7" plcIndex="6"  page="0" target-confirm="true"
				product-admin="true" product-label-x="411" product-label-y="450"
				tag-x="411" tag-y="460">
				<img name="s7" img-x="411" img-y="565"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s8" plcIndex="7"  page="0" target-confirm="true"
				product-admin="true" product-label-x="1024" product-label-y="450"
				tag-x="1024" tag-y="460">
				<img name="s8" img-x="1024" img-y="535"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s9" plcIndex="8"  page="0" target-confirm="true"
				product-admin="true" product-label-x="1065" product-label-y="450"
				tag-x="1065" tag-y="460">
				<img name="s9" img-x="1065" img-y="586"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s10" plcIndex="9"  page="0" target-confirm="true"
				product-admin="true" product-label-x="1104" product-label-y="450"
				tag-x="1104" tag-y="460">
				<img name="s10" img-x="1104" img-y="586"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s11" plcIndex="10"  page="0" target-confirm="true"
				product-admin="true" product-label-x="1144" product-label-y="450"
				tag-x="1144" tag-y="460">
				<img name="s11" img-x="1144" img-y="586"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s12" plcIndex="11"  page="0" target-confirm="true"
				product-admin="true" product-label-x="1184" product-label-y="450"
				tag-x="1184" tag-y="460">
				<img name="s12" img-x="1184" img-y="586"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s13" plcIndex="12"  page="0" target-confirm="true"
				product-admin="true" product-label-x="1224" product-label-y="450"
				tag-x="1224" tag-y="460">
				<img name="s13" img-x="1224" img-y="586"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s14" plcIndex="13"  page="0" target-confirm="true"
				product-admin="true" product-label-x="1274" product-label-y="450"
				tag-x="1274" tag-y="460">
				<img name="s14" img-x="1274" img-y="586"/>
				<level checking="none" />		
			</silo>	            
	    
			<silo name="s15" plcIndex="14"  page="1" 
				product-admin="true" product-label-x="135" product-label-y="450"
				tag-x="135" tag-y="460">
				<img name="s15" img-x="141" img-y="570"/>
				<level checking="none" />		
			</silo>	            
	    	    
			<silo name="s17" plcIndex="16"  page="1" 
				product-admin="true" product-label-x="251" product-label-y="500"
				tag-x="251" tag-y="510">
				<img name="s17" img-x="251" img-y="548"/>
				<level checking="none" />		
			</silo>	            
			    			    
			<silo name="s19" plcIndex="18"  page="1"
				product-admin="true" product-label-x="331" product-label-y="500"
				tag-x="331" tag-y="510">
				<img name="s19" img-x="331" img-y="548"/>
				<level checking="none" />		
			</silo>	            
			    
			<silo name="s20" plcIndex="19"  page="1"
				product-admin="true" product-label-x="371" product-label-y="500"
				tag-x="371" tag-y="510">
				<img name="s20" img-x="371" img-y="548"/>
				<level checking="none" />		
			</silo>	            

			<offsetCorrector name="oc1" plcIndex="15"  page="0" receiveCorrection="3" transmitCorrection="3"/>
			<offsetCorrector name="s18" plcIndex="17"  page="0" receiveCorrection="3" transmitCorrection="3"/>
			<offsetCorrector name="s21" plcIndex="20"  page="0" receiveCorrection="3" transmitCorrection="3"/>
			<offsetCorrector name="46" plcIndex="46"  page="0" receiveCorrection="4" transmitCorrection="4"/>
			<offsetCorrector name="18" plcIndex="48"  page="0" receiveCorrection="4" transmitCorrection="4"/>
			<offsetCorrector name="33a" plcIndex="64"  page="0" receiveCorrection="1" transmitCorrection="1"/>
			<offsetCorrector name="29.1" plcIndex="77"  page="0" receiveCorrection="3" transmitCorrection="3"/>

			<targetSilo name="s22" plcIndex="21"  page="0" permeability="0.7">
				<img name="s22" img-x="746" img-y="486"/>
				<level checking="switching" full-is-off-task="false" test = "4">
					<full name="tr_level" img-x="840" img-y="475" maxthresold="95"/>
					<empty name="tr_level" img-x="840" img-y="425" minthresold="5"/>
				</level>
			</targetSilo>	            

			<targetSilo name="s23" plcIndex="22"  page="1">
				<img name="s23" img-x="705" img-y="374"/>
				<level checking="switching" full-is-off-task="false" test = "3"> 
					<full name="tr_level" img-x="780" img-y="360" maxthresold="95"/>
					<empty name="tr_level" img-x="780" img-y="310" minthresold="5"/>
				</level>				
			</targetSilo>	            

			<targetSilo name="s24" plcIndex="23"  page="0" >
				<img name="s24" img-x="810" img-y="219"/>
				<level checking="full-only" name="tr_level" img-x="819" img-y="187"/>		
			</targetSilo>	            

			<targetSilo name="s25" plcIndex="24"  page="0">
				<img name="s25" img-x="855" img-y="219"/>
				<level checking="full-only" name="tr_level" img-x="864" img-y="187"/>		
			</targetSilo>	            
 			
			<targetSilo name="s30" plcIndex="29"  page="1">
				<img name="s30" img-x="1031" img-y="417"/>
				<level checking="full-only" name="tr_level" img-x="1048" img-y="400"/>		
			</targetSilo>	            

			<targetSilo name="s31" plcIndex="30"  page="1">
				<img name="s31" img-x="1075" img-y="417"/>
				<level name="tr_level" checking="full-only" img-x="1092" img-y="400"/>		
			</targetSilo>	            

			<ponderingSilo name="M3" plcIndex="25"  page="0" format="%5.1f" label-x="603" label-y="768"
				empty-limit="1.0" full-limit="1.0" product-admin="true" product-label-x="615" product-label-y="720">
				<level checking="none" />		
				<img name="m3" img-x="615" img-y="230"/>
				<scale type="MS01" name="M26" port="moxa0" address="A" divide="100" max-load="11500" input-format="###q" test="43.0"/>
				<remote-server port="7502"/>
				<!-- remote-client host-address="192.168.0.52" port="7502"/-->		
			</ponderingSilo>	            
 			
			<ponderingSilo name="M2" plcIndex="26" page="0" format="%5.1f" label-x="645" label-y="805"
				empty-limit="1.0" full-limit="1.0" product-admin="true" product-label-x="657" product-label-y="720">
				<level checking="none" />		
				<img name="m2" img-x="657" img-y="230"/>
				<scale type="MS01" name="M28" port="moxa2" address="A" divide="100" max-load="11500" input-format="###q" test="42.0"/>		
				<remote-server port="7501"/>
                <!-- remote-client host-address="192.168.0.52" port="7501"/-->	
			</ponderingSilo>	            

			<ponderingSilo name="M1" plcIndex="27" page="0" format="%5.1f" label-x="690" label-y="768"
				empty-limit="1.0" full-limit="1.0" product-admin="true" product-label-x="699" product-label-y="720">
				<level checking="none" />		
				<img name="m1" img-x="699" img-y="230"/>
				<scale type="MS01" name="M29" port="moxa3" address="A" divide="100"	max-load="11500" input-format="###q" test="41.0"/>	
				<remote-server port="7500"/>
                <!-- remote-client host-address="192.168.0.52" port="7500"/-->
