=== iwannabedeewo/thesis-work/lib/bdevossa_plcopen.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="plcProject">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="projectInfo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="modificationDateTime" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="date" type="xs:date" use="required"/>
									<xs:attribute name="time" type="xs:time" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="authors"> 
								<xs:complexType>
									<xs:sequence>
										<xs:element name="author" type="person" maxOccurs="10"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="customer" type="customer"/>
						</xs:sequence>
						<xs:attribute name="projectName" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="3"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="productName" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="3"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="companyName" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="3"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="version" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string"> 
									<xs:pattern value="[0-9](.[0-9][0-9]*)+" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="creationDate" type="xs:date" use="required" />
						<xs:attribute name="creationTime" type="xs:time" use="required" />
						<xs:attribute name="git" type="xs:string" />
						<xs:attribute name="interfaceBaseAddress" type="xs:integer" />
					</xs:complexType>
				</xs:element>

				<xs:element name="application">
					<xs:complexType>
						<xs:sequence>
						
							<xs:element name="emergency">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="INPUT" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="bit" type="xs:string" />
											</xs:complexType>
										</xs:element>
										<xs:element name="OUTPUT">
											<xs:complexType>
												<xs:attribute name="bit" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="marker" type="xs:string" />
								</xs:complexType>
							</xs:element>

							<xs:element name="task">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="watchdog" type="watchdog" minOccurs="0"/>
										<xs:element name="pous">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Motor" type="pou_MOTOR" />
													<xs:element name="StateIn" type="pou_STATEIN" />
												</xs:sequence>
											</xs:complexType>
											<xs:unique name="priority_key">
												<xs:selector xpath="*"/>
												<xs:field xpath="@priority"/>
											</xs:unique>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="interval" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="1000" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="intervalUnit" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="ms|us"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute ref="priority" use="required" />
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="cyclic|event|freewheeling|status" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
					</xs:complexType>
				</xs:element> <!-- APPLICATION END -->
				
			</xs:sequence>
		</xs:complexType>
	</xs:element> <!-- PLCPROJECT END -->

	<!-- ============================== ComplexType Definitions ============================== -->
	<xs:complexType name="variable">
		<xs:attribute name="address" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[IQM]X[0-9].[0-9]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="pou">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="type" default="st">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="st|ST|ld|LD|fbd|FBD" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute ref="priority" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="pou_MOTOR">
		<xs:complexContent>
			<xs:extension base="pou">
				<xs:sequence>
					<xs:element name="INPUT" type="variable" />
					<xs:element name="STOP" type="variable" />
					<xs:element name="OUTPUT" type="variable" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="pou_STATEIN">
		<xs:complexContent>
			<xs:extension base="pou">
				<xs:sequence>
					<xs:element name="INPUT" type="variable" />
					<xs:element name="OUTPUT" type="variable" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="watchdog">
		<xs:attribute name="enabled" type="xs:boolean" />
		<xs:attribute name="timeUnit" default="us">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="ms|us"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="sensitivity">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1" />
					<xs:maxInclusive value="1000" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="person">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute ref="telNumber" use="required" />
		<xs:attribute ref="email" use="required" />
	</xs:complexType>

	<xs:complexType name="person_contact">
		<xs:complexContent>
			<xs:extension base="person">
				<xs:attribute name="role" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="customer">
		<xs:complexContent>
			<xs:extension base="person">
				<xs:sequence>
					<xs:element name="contact" type="person_contact" maxOccurs="10"/>
				</xs:sequence>
				<xs:attribute name="country" type="xs:string" use="required" />
				<xs:attribute name="zip" type="xs:integer" use="required" />
				<xs:attribute name="city" type="xs:string" use="required" />
				<xs:attribute name="address" type="xs:string" use="required" />
				<xs:attribute name="web" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- ============================== Attribute Definitions ============================== -->
	<xs:attribute name="priority">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1" />
				<xs:maxInclusive value="1000" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="telNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="(06|\+36)[0-9]{9}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:attribute name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value=".+@.+\..+"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

</xs:schema>

=== iwannabedeewo/thesis-work/src/testSrc.xml
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE xml>
<plcProject
    xmlns:bdevossaPLC="http://www.w3.org/2001/XMLSchema-instance"
    bdevossaPLC:noNamespaceSchemaLocation="..\lib\bdevossa_plcopen.xsd">

	<projectInfo projectName="First Test" productName="TEST ST PLC" companyName="Almighty ZRT11" version="0.1.23.456" 
	    creationDate="1990-01-01" creationTime="12:00:00" git="https://github.com/iwannabedeewo/thesis-work" interfaceBaseAddress="4000"> 
			<modificationDateTime date="2016-04-10" time="17:37:00"/>
			<authors> 
				<author name="a1" telNumber="06123456789" email="a1@a1.com"/>  
				<author name="a2" telNumber="+36123456789" email="a2@a1.com"/> 
			</authors>
			<customer name="Pistám" country="Hungary" zip="5900" city="Orosháza" address="asd" telNumber="+36123456789" email="test@pelda.com">
				<contact name="c1" role=""  telNumber="+36123456789" email="cont1@pelda.com"/>
				<contact name="c2" role="" telNumber="06301239876" email="cont22@test.com"/> 
			</customer> 
	</projectInfo>
		
	<application> 
		<emergency marker="m0">
			<INPUT bit="x0"/>
			<INPUT bit="x1"/> 
			<INPUT bit="x2"/>
			<OUTPUT bit="y1"/>
		</emergency>
		
		<task name="ExampleTask" interval="20" intervalUnit="ms" priority="1" type="cyclic">
			<pous> 
				<Motor name="Ontarto" priority="1">
					<INPUT address="IX0.0"/>
					<STOP address="MX0.0"/>
					<OUTPUT address="QX0.0"/>
				</Motor> 
				 
				<StateIn name="StateInExample" priority="2">
					<INPUT address="IX0.0"/>
					<OUTPUT address="QX0.0"/>
				</StateIn>
			</pous>
		</task>
		
	</application>
</plcProject>
